[project]
name = "dagster-deployment"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "dagster",
    "dagster-aws", 
    "dagster-postgres",
]

[project.optional-dependencies]
webserver = [
    "dagster-webserver",
    "dagster-graphql",
]