s3:
  bucket_name: "dagster-acled-bucket"
  data_prefix: "acled/acled_daily_data"
  reports_prefix: "acled/reports"
  models_prefix: "acled/models"

postgres:
  table_name: "acled_events_no_delete"
  schema: "public"

storage_account: 
  name: "acledbucket"
  url: "https://acledbucket.blob.core.windows.net/"
  container: "acled-container"

keyvault:
  url: "https://acled-keys.vault.azure.net/"
